### ISSUE TITLE
SPIKE: Determine feasibility of controlling preservation event by adding a triple

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/pushmi_pullyu#13]

**Comment by murny** [comment]
Is it possible to get more details for this? What does "adding a triple" mean with regards to ERA?

**Comment by sfbetz** [comment]
@pbinkley I think this will require clarification from you.

**Comment by pbinkley** [comment]
This was intended to capture the idea we discussed at grooming last week of letting the application set a unique triple to express the status of a given item needing a preservation action, so that Pushmi-pullyu could simply watch for that change in the JMS stream. We weren't certain of the best way of expressing this so as to minimize load on Fedora while conveying the id of the item efficiently. So this issue was intended to cover the investigation needed to work out what the best approach would be.

**Comment by pbinkley** [comment]
This question has been replaced by the need for an after_save process in HydraNorth / HydraNorth2, to put the triggering of preservation events entirely under the control of the application.
