### ISSUE TITLE
Logging requirements for PushmiPullyu

### ISSUE THREAD

**Issue by cwant** [ualbertalib/pushmi_pullyu#144]
This ticket is spun off from a jupiter requirement in this ticket: https://github.com/ualbertalib/jupiter/issues/354

`Update logging to ensure it includes the following information:
object identifier, object bag's checksum, file sizes of the original files in the bag, file types of the original files in the bag.`

This requirement is related to generating reports on preservation activities, but needs further development to capture the full details of the work.

**Comment by weiweishi** [comment]
@pbinkley, following up on this issue:
this is a sample of the current preservation event log:
```
I, [2017-11-17T07:10:00.442154 #4616]  INFO -- : test01rb68xb849 was successfully deposited into Swift Storage! 
Here are the details of this preservation event: 
	 NOID: 'test01rb68xb849' 
	 Timestamp of Completion: 'Fri, 17 Nov 2017 14:10:01 GMT' 
	 AIP Checksum: 'b89bd3a4d99e12b388aa1f2713d923e8' 
	 Metadata: {"project-id"=>"test01rb68xb849", "aip-version"=>"1.0", "project"=>"ERA", "promise"=>"bronze"} 
```
Would it be okay/feasible if we add something like this:
```File Details:
    fileset_uuid1: content-type: pdf; size: 3826356 bytes
    fileset_uuid2: content-type: txt; size: 934735 bytes
```

**Comment by pbinkley** [comment]
That looks good. Those lines would presumably be indented to show their subordination to the main INFO line.

**Comment by murny** [comment]
Seems to be more work then anticipated?

The preservation event log that we are talking about here is when the TAR file (which contains the objects (files and metadata), logs, and bag/checksums info) gets deposited into Swift. 

So we cannot easily get individual file metrics here? Because they are hidden within the tar file. 

So best option is we want to find the tar file we just uploaded, unpacking this (or use it's original directory before it was tarred which is still on the filesystem), looking up the files location within this folder and outputting this to the logs, which is a bit more work then simply just updating the logs. 

With that said however, we can easily get these metrics about the TAR file itself. Such as its size and its type (which is always going to be, well a tar file)

So I'lll continue working on a way to do this, unless someone says this is low priority or just having the TAR metrics (size/type) is good enough?

**Comment by pbinkley** [comment]
I'll check with Umar about this. Making PMPY responsible at the TAR level
and another post-process responsible for pulling manifests out of tars to
populate a db for Umar's content reports would certainly be doable, and a
cleaner separation of responsibility.

**Comment by murny** [comment]
With regard to the outputting of this does this sound reasonable?
```
I, [2017-11-17T07:10:00.442154 #4616]  INFO -- : test01rb68xb849 was successfully deposited into Swift Storage! 
Here are the details of this preservation event: 
	 NOID: '01bb1b09-974d-478b-8826-2c606a447606' 
	 Timestamp of Completion: 'Fri, 17 Nov 2017 14:10:01 GMT' 
	 AIP Checksum: 'b89bd3a4d99e12b388aa1f2713d923e8' 
	 Metadata: {"project-id"=>"test01rb68xb849", "aip-version"=>"1.0", "project"=>"ERA", "promise"=>"bronze"} 
         File Details:
           fileset_uuid: 837977d6-de61-49ea-a912-a65af5c9005e, file_name: "image-sample.jpeg"; content-type: jpeg; size: 12401 bytes;
           fileset_uuid: 856444b6-8dd5-4dfa-857d-435e354a2ead, file_name: "era-logo.png"; content-type: png size: 5612 bytes;
```

So changes from above are basically adding printing out the file name as well? 

I doubt this will ever happen but their could be the situation where a file set has multiple files for whatever reason? With this change, it just works, you will just see fileset_uuid listed twice in the log with the two different files in the file set.

**Comment by weiweishi** [comment]
Thanks @murny this looks good to me. It is unlikely that we will have a file set that has multiple files in it, from ERA anyway. But we can always parse the info out if not needed - and it might become handy in some cases.

**Comment by pbinkley** [comment]
This looks great.

**Comment by weiweishi** [comment]
Looks good to me! :+1:

**Comment by pbinkley** [comment]
​Likewise.​ +1
